mode: "image"  # Chọn chế độ: train, image, video, realtime
filter: True
# Tham số cho chế độ train
epochs: 1
learning_rate: 0.0001
batch_size: 32
num_workers: 6
test_size: 0.2

# Đường dẫn đến model đã train
model_path: /home/phong/PycharmProjects/Filter_RN50/checkpoint/test.pth

# Đường dẫn đến ảnh hoặc video
image_path: /home/phong/PycharmProjects/Filter_RN50/Test/Image/test12.jpg
video_path: /home/phong/PycharmProjects/Filter_RN50/Test/Video/test1.mp4